FROM ruby:3.3-alpine

# Install development dependencies
RUN apk add --no-cache \
    build-base \
    postgresql-dev \
    git \
    curl \
    bash

# Set working directory  
WORKDIR /app

# Copy Gemfile and install gems (including development gems)
COPY Gemfile Gemfile.lock ./
RUN bundle config set --local without 'production' && \
    bundle install

# Create directories for logs and tmp
RUN mkdir -p log tmp blueprintsCLI

COPY ../lib /app/blueprintsCLI/

# Expose port 3000
EXPOSE 3000

# For development, we'll mount the code as a volume
# and use rerun for auto-reloading
CMD ["bundle", "exec", "rerun", "--background", "--signal", "TERM", "rackup config.ru -o 0.0.0.0 -p 3000"]