# frozen_string_literal: true

source 'https://rubygems.org'

# Core web framework
gem 'rack', '~> 3.1'
gem 'rack-cors', '~> 2.0'
gem 'rackup', '~> 2.1'
gem 'rake'
gem 'sinatra', '~> 4.1'
# JSON handling
gem 'json', '~> 2.8'

# Database and ORM
gem 'pg', '~> 1.6'
gem 'sequel', '~> 5.95'

# Development and testing
group :development, :test do
  gem 'pry', '~> 0.15'
  gem 'rerun', '~> 0.14'
  gem 'webrick', '~> 1.8'
end

# Production web server
group :production do
  gem 'puma', '~> 6.4'
end

gem 'dotenv', '~> 3.1'
gem 'redis', '~> 5.4'
